# -*- coding: utf-8 -*-
"""decodelabsp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GrPq4P_kM_WbkYPoT6_BeSwRDaDknnAh
"""

### TASK 1: DATA COLLECTION & DATASET UNDERSTANDING ###

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


df = pd.read_csv("Teen_Mental_Health.csv")

df.head()

df.shape
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

df.columns

df.describe()

df.isnull().sum()

"""This dataset contains information related to teen mental health,
sleep habits, social media usage, academic performance, and
behavioral patterns. the columns represent demographic, behavioral, and mental health-related features. while the rows represent 1 student observation.

number of rows: 1200
number of columns: 16
dataset has zero missing values and ut includes both numerical and categorial data types.
"""

##### TASK 4: DATA VISUALIZATION #####

#visualization 1
sns.histplot(df["stress_level"], bins=10)
plt.title("Distribution of Student Stress Levels")
plt.xlabel("Stress Level")
plt.ylabel("Count")
plt.show()

#visualization 2
sns.scatterplot(x="sleep_hours", y="depression_label", data=df)
plt.title("Relationship Between Sleep Hours and Depression")
plt.show()

#visualization 3
sns.boxplot(x="gender", y="anxiety_level", data=df)
plt.title("Anxiety Levels Across Gender Categories")
plt.show()

#visualization 4
corr = df.corr(numeric_only=True)

sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

##### TASK 5: Predictive Model or Insight Project #####

le = LabelEncoder()

categorical_cols = [
    "gender",
    "platform_usage",
    "social_interaction_level",
    "sleep_quality",
    "digital_wellbeing_flag"
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

X = df.drop("depression_label", axis=1)

Y = df["depression_label"]

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2,random_state=42, stratify=Y
)

model = RandomForestClassifier(random_state=42, class_weight="balanced")

model.fit(X_train, Y_train)

predictions = model.predict(X_test)

accuracy = accuracy_score(Y_test, predictions)

print("Accuracy:", accuracy)
print(classification_report(Y_test, predictions))

"""A Random Forest classification model was developed
to predict depression labels using behavioral and
mental health-related features.

Categorical variables were encoded using Label Encoding,
and class balancing was applied due to dataset imbalance.

"""